name: Publish Release Artifacts

on:
  release:
    types:
      - created

jobs:
  publish-release-artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Alfred workflow
        run: |
          mkdir -p target
          cd workflow && zip -r ../target/alfred-datetime-format-converter.alfredworkflow . -x "*.pyc" -x "__pycache__/*" -x "*/__pycache__/*"
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: target/alfred-datetime-format-converter.alfredworkflow
          asset_name: alfred-datetime-format-converter.alfredworkflow
          asset_content_type: application/zip
